---
resources:
- name: concourse-test
  type: git
  source:
    uri: https://github.com/LiYa-Xu/concourse-test.git
    branch: master

jobs:
- name: email-test
  public: true
  plan:
  - get: concourse-test
  - task: email-test
    file: concourse-test/test.yml
